site_name: F1 Technical Authoring Demo

theme:
  name: material
  features:
    - navigation.footer

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Using Orbit CRM:
      - Overview: overview.md
      - Create a customer: create-customer.md
      - Example - Create a customer: example-create-customer.md
  - Reference:
      - Customer fields: customer-fields-reference.md
  - Troubleshooting:
      - Customer creation issues: troubleshooting-customer-creation.md
  - Account settings: account-settings.md
